### ISSUE TITLE
时间戳转换问题

### ISSUE THREAD

**Issue by ripperhe** [ccimage/jsonviewer#1]
插件转换出来的结果如下

![Jietu20190620-095145](https://user-images.githubusercontent.com/13943595/59812582-1e2e0300-9341-11e9-8274-1b04d8050974.png)

但是我用网站的工具转换如下

![Jietu20190620-095218](https://user-images.githubusercontent.com/13943595/59812616-33a32d00-9341-11e9-940c-b2738ee3d2f6.png)

我是要设置一下时区还是什么吗？怎么解决呢？

比如这个时间戳 1561611015927

**Comment by ccimage** [comment]
插件默认显示的是GMT标准时间0时区的。 鼠标浮上去会有提示当地时区的时间。
