### ISSUE TITLE
"parseError": "Invalid character '\n' at position 43"

### ISSUE THREAD

**Issue by mohammadMahdiAghajani** [ccimage/jsonviewer#11]
error
{
  "parseError": "Invalid character '\n' at position 43"
}

json file

{"a":1,"b":2,"c":{"qw":23,"qe":24,"qr":"new\nline"}}

**Comment by AidanWelch** [comment]
Also errors with `\r`

**Comment by hithesh-sankararaman** [comment]
Facing the same error.
parseError": "Invalid character '\n' at position

**Comment by ccimage** [comment]
fixed on version 1.5.1
