### ISSUE TITLE
Json viewer will break (cannot be rendered properly) if there is a text `</script>` in any json strings

### ISSUE THREAD

**Issue by johnnytemp** [ccimage/jsonviewer#7]
E.g. With this json:

`{"key": "</script>ABC"}`

The json viewer will not be render-able. It will just show the following text without GUI controls:

`ABC"})`

**Comment by johnnytemp** [comment]
I guess it might possibly be fixed if the program replace `</script>` to `<\/script>` when putting some JSON content to JavaScript.

**Comment by ccimage** [comment]
i've not noticed this issue for months.
fixed in 1.3.3
thx
