### ISSUE TITLE
uint64 numbers are displayed incorrectly

### ISSUE THREAD

**Issue by danoldmac** [ccimage/jsonviewer#8]
Hello,
I've found that uint64_t numbers are shown incorrectly in VS Code (JSON Viewer v1.3.2).

For example the value of field  "ItemsPersistentIdentifiers": [ 3183234085794734210] was shown as 3183234085794734000.
The value of field  "system_time": 1692197812390106667, in the JSON viewer was shown as 1692197812390106600

Part of json file:
 {
           "metadata": {
            "iap2": {
                "id": 19463,
                "name": "PlayMediaLibraryItems"
            },
            "identity": "iAP2.Message.PlayMediaLibraryItems",
            "source": "accessory",
            "status": null,
            "system_time": 1692197812390106667,
            "system_time_formatted": "17:56:52.390",
            "timestamp": 110867725867,
            "timestamp_formatted": "1:50.867",
            "title": "PlayMediaLibraryItems",
            "transport": "usb"
        },
        "Parameters": {
            "ItemsPersistentIdentifiers": [
                3183234085794734210
            ],
            "ItemsStartingIndex": 0,
            "MediaLibraryUniqueIdentifier": "48511AF4-1979-4EAD-80CE-DDFWSDF-MPB-16.6"
        },
        "Summary": {
            "ID": "0x4C07",
            "Length": 76,
            "Name": "PlayMediaLibraryItems"
        }
    },

**Comment by ccimage** [comment]
yes. I reproduce the bug，and trying to fix it.
Maybe the reason is javascript has low precision.

**Comment by ccimage** [comment]
fixed after update to 1.4.0
but another issue arises:
if string value with the letter ", the escape character will always shows (as \")

**Comment by danoldmac** [comment]
The mentioned issue is fixed. Thanks.
