### ISSUE TITLE
格式化成json格式后，会自动滑动到最右侧

### ISSUE THREAD

**Issue by wangzhebuzai** [ccimage/jsonviewer#9]
当使用这个插件把文本格式化成json格式后，会把水平滚动条自动滑到最右侧，但是base64的文本很长不方便看到整体结构，建议自动滑到最左侧

**Comment by ccimage** [comment]
好的  等有时间研究一下这个问题

**Comment by wangzhebuzai** [comment]
您好，您发给我的邮件已受到，谢谢！我会尽快回复。

**Comment by ccimage** [comment]
请问能提供一下原文件吗？如何操作？ 我不知道怎么复现这个问题

**Comment by wangzhebuzai** [comment]
当我粘贴一个value很长的json后，此时光标是停在这个字符串结尾的，这时候我用工具---格式化语言--格式化json，就会把文字格式化成json格式，然后水平方向的滚动条会停留在最右侧
json字符串示例：
{"1":null,"10":null,"11":"本站为每个网友提供免费5次使用直链的次数本站为每个网友提供免费5次使用直链的次数本站为每个网友提供免费5次使用直链的次数本站为每个网友提供免费5次使用直链的次数本站为每个网友提供免费5次使用直链的次数本站为每个网友提供免费5次使用直链的次数本站为每个网友提供免费5次使用直链的次数本站为每个网友提供免费5次使用直链的次数本站为每个网友提供免费5次使用直链的次数","2":"测试","3":"重庆","4":15,"5":"GGXH-2308","6":null,"7":"机械","8":"本站为每个网友提供免费5次使用直链的次数本站为每个网友提供免费5次使用直链的次数本站为每个网友提供免费5次使用直链的次数本站为每个网友提供免费5次使用直链的次数本站为每个网友提供免费5次使用直链的次数本站为每个网友提供免费5次使用直链的次数","9":null}


粘贴后



点击这个菜单





结果展示












&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ccimage/jsonviewer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月25日(星期一) 中午1:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ccimage/jsonviewer] 格式化成json格式后，会自动滑动到最右侧 (Issue #9)





 
请问能提供一下原文件吗？如何操作？ 我不知道怎么复现这个问题

**Comment by ccimage** [comment]
![image](https://github.com/ccimage/jsonviewer/assets/1228378/9a01213c-db83-47e1-9c52-c8c5da428f24)
你可能在邮件回复中粘贴了图片，但是github上看不到。
我的插件只提供了一个菜单  Open in json viewer 打开后的结果就如上图所示。 并没有滚动条。

**Comment by wangzhebuzai** [comment]
那我们说的就不是一个问题了，你的图是左侧的目录部分，我说的是右侧的正文不问，正文部分是有水平和垂直滚动条的







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ccimage/jsonviewer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月26日(星期二) 中午12:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ccimage/jsonviewer] 格式化成json格式后，会自动滑动到最右侧 (Issue #9)





 

 你可能在邮件回复中粘贴了图片，但是github上看不到。
 我的插件只提供了一个菜单  Open in json viewer 打开后的结果就如上图所示。 并没有滚动条。

**Comment by ccimage** [comment]
很抱歉，由于看不到截图，有点get不到这个问题。
工具---格式化语言--格式化json  
我的插件没有提供这个菜单啊。

**Comment by wangzhebuzai** [comment]
您好，您发给我的邮件已受到，谢谢！我会尽快回复。

**Comment by wangzhebuzai** [comment]
这个问题在更新版本后消失了







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ccimage/jsonviewer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月16日(星期五) 中午11:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ccimage/jsonviewer] 格式化成json格式后，会自动滑动到最右侧 (Issue #9)





 
很抱歉，由于看不到截图，有点get不到这个问题。
 工具---格式化语言--格式化json
 我的插件没有提供这个菜单啊。

**Comment by wangzhebuzai** [comment]
您好，您发给我的邮件已受到，谢谢！我会尽快回复。
